### PR TITLE
Fixes issue #10

### PR DESCRIPTION
**Pull request by anonfunc**
Create a new window if one does not exist, even if iTerm is running.

### CODE REVIEW

**Comment by stuartcryan** [comment]
Hi anonfunc,
Just wanted to let you know that I have seen your pull request, currently this weekend I am in lockdown for assignment work (assignments due Monday) so I will have a look at this within the next week.
Cheers,
Stuart

**Comment by stuartcryan** [comment]
Awesome :) looks good #merging

**Comment by dserodio** [comment]
Are this and #10 not needed for iTerm 2.9 ?

**Comment by stuartcryan** [comment]
@dserodio The code is very different (the scripts were build independently as the applescipt functions have changed significantly in the 2.9 branch of iTerm.

These should not be a problem in the other branch as a result of it being largely different (and as I am running it solely now) far better tested.

Thus far I haven't had reports of a similar issue in the 2.9 branch.
Cheers,
Stuart

**Pull request merged**
